export { default as Actors } from "./Actors/Actors";
export { default as MovieInfo } from "./MovieInfo/MovieInfo";
export { default as Movies } from "./Movies/Movies";
export { default as Profile } from "./Profile/Profile";
export { default as Navbar } from "./NavBar/NavBar";
export { default as Sidebar } from "./Sidebar/Sidebar";
export { default as MoviesList } from "./MoviesList/MoviesList";
export { default as Movie } from "./Movie/Movie";
export { default as Spinner } from "./Spinner/Spinner";
